### ISSUE TITLE
aboutTabs.html bug

### ISSUE THREAD

**Issue by ghost** [webcrunch/macklare#1]
'Kontakt' is not displaying properly on smaller screens. Probably due to the html code in the directive containing its own containers, rows and cols and overrides the parent.

**Comment by patofloyd** [comment]
Från och med Far gjorde de sista ändringarna på utseende blev kontakta oss sidan så där. Faj kommer att länka sidan till kontakt som ligger på om oss sida.

**Comment by ghost** [comment]
den jag syftar på är "Om oss" och sen tabben "Kontakt". Förminskar man skärmytan där så hamnar allt utanför till höger. Det beror på att direktivets template innehåller sina egna containers, rows och cols. Jag kan fixa det, men hade inte tid just nu. Så om ingen annan gör det så löser vi det i veckan som kommer :)

**Comment by patofloyd** [comment]
Ja precis. Jag är på vägen till Barcelona så jag kan inte fixa något fram till tisdag. På onsdag är jag ledig om det saknas något (sista dagen faktiskt hahahaha)
